env:
  browser: true
  jquery: true
  es6: true

plugins:
  - react-hooks

extends:
  - 'indico'
  - 'indico/babel'
  - 'indico/react'

settings:
  # we don't use the webpack resolver because it is SLOW (~1s),
  # but our custom resolver does the job just fine while still
  # being fast.
  import/resolver:
    alias:
      map:
        - ['indico/modules/core', './indico/modules/core/client/js']
        - ['indico/modules/rb_new', './indico/modules/rb_new/client/js']
        - ['indico', './indico/web/client/js']
      extensions: [.js, .jsx, .json]
  react:
    version: '16.6.3'

rules:
  func-style:
    - warn
    - declaration
    - allowArrowFunctions: true
  import/no-unresolved:
    - error
    - ignore: ['^indico-url:']
  new-cap:
    - error
    - capIsNewExceptionPattern: '\$\.(Event|Deferred)$'
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
  prefer-template: warn
  react/forbid-component-props: off
  react-hooks/rules-of-hooks: error

globals:
  Indico: false
  IndicoUI: false
  global: false
  require: false
  process: false
